# SPDX-License-Identifier: (LicenseRef-KooijmanInc-Commercial OR GPL-3.0-only)
# Copyright (c) 2025 Kooijman Incorporate Holding B.V.

# GitHub Sponsors & funding links
# Fill in the handles/ids you actually use, then place this file at .github/FUNDING.yml

github: [KooijmanInc]            # e.g. ["kooijmaninc"]
patreon: "Sebastiaan Kooijman"           # e.g. "kooijman"
open_collective: Genesis-X
ko_fi: Kooijman
tidelift: pypi/genesis-x
custom:               # direct links (PayPal, Stripe, Buy Me a Coffee, etc.)
  - https://paypal.me/kooijmaninc
  - https://buy.stripe.com/6oUfZh67X1n67FC4NVaAw01
  - https://buy.stripe.com/3cIaEXeEt1n66BybcjaAw00

