# SPDX-License-Identifier: (LicenseRef-KooijmanInc-Commercial OR GPL-3.0-only)
# Copyright (c) 2025 Kooijman Incorporate Holding B.V.

stages: [release]

github_release:
  image: alpine:3.19
  stage: release
  rules: [ { if: '$CI_COMMIT_TAG' } ]   # runs only for tags
  variables:
    REPO: KooijmanInc/Genesis-X
  before_script:
    - apk add --no-cache curl jq
  script:
    - |
      curl -s -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/$REPO/releases \
        -d @- <<JSON
      {
        "tag_name": "$CI_COMMIT_TAG",
        "name": "Genesis-X ${CI_COMMIT_TAG#v}",
        "body": "Release $CI_COMMIT_TAG",
        "draft": false,
        "prerelease": false,
        "generate_release_notes": true
      }
      JSON

