blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/KooijmanInc/Genesis-X/security/policy
    about: Please do not report security vulnerabilities in public issues.
