# SPDX-License-Identifier: (LicenseRef-KooijmanInc-Commercial OR GPL-3.0-only)
# Copyright (c) 2025 Kooijman Incorporate Holding B.V.

DESTINATION_PATH = $$PLATFORM_PATH/$$COMPILER_PATH/$$PROCESSOR_PATH/$$BUILD_PATH
LOCAL_DESTINATION_PATH = $$PLATFORM_PATH/$$COMPILER_PATH/$$PROCESSOR_PATH

